### ISSUE TITLE
Incorrect app status displayed when optimiser cannot find suitable node candidates

### ISSUE THREAD

**Issue by atsag** [eu-nebulous/optimiser-controller#31]
While trying to deploy the simple rest api controller application Robert has created, it immediately was set to "deployed" (as soon as I clicked on 'deploy') and I found the logs below to be possibly associated to the event:

{"@timestamp":"2024-10-04T14:47:35.896599372Z","@version":"1","message":"Processing message fortopic://eu.nebulouscloud.cfsb.get_node_candidates_multi.reply","logger_name":"eu.nebulouscloud.exn.core.Consumer","thread_name":"pool-12-thread-11","level":"DEBUG","level_value":10000}
{"@timestamp":"2024-10-04T14:47:35.930268645Z","@version":"1","message":"Could not find node candidates for requirements: [class AttributeRequirement {\n    class Requirement {\n        type: AttributeRequirement\n    }\n    requirementClass: hardware\n    requirementAttribute: ram\n    requirementOperator: GEQ\n    value: 8192\n}, class AttributeRequirement {\n    class Requirement {\n        type: AttributeRequirement\n    }\n    requirementClass: hardware\n    requirementAttribute: cores\n    requirementOperator: GEQ\n    value: 4\n}], aborting deployment","logger_name":"eu.nebulouscloud.optimiser.controller.NebulousAppDeployer","thread_name":"Thread-4","level":"ERROR","level_value":40000,"appId":"b8f355fb-5001-43a6-bc6b-dcb3a46ffe8f","clusterName":"b8f35-5"}
{"@timestamp":"2024-10-04T14:47:35.930674856Z","@version":"1","message":"topic://eu.nebulouscloud.optimiser.controller.app_state Sending {state=FAILED}-> null ","logger_name":"eu.nebulouscloud.exn.core.Publisher","thread_name":"Thread-4","level":"DEBUG","level_value":10000,"appId":"b8f355fb-5001-43a6-bc6b-dcb3a46ffe8f","clusterName":"b8f35-5"}

The deployment did not initiate any VMs.

**Comment by rudi** [comment]
Hi, the deployment failed since we didn't find a suitable VM for the controller node (8GB memory, 4 cores).  The log is emitted here: https://github.com/eu-nebulous/optimiser-controller/blob/0110dd8970db8e1fd8346e0bb2b2b08069e23376/optimiser-controller/src/main/java/eu/nebulouscloud/optimiser/controller/NebulousAppDeployer.java#L415

On the next line, we tell the app to set itself to a failed state, which causes the app to emit a message that deployment failed: https://github.com/eu-nebulous/optimiser-controller/blob/0110dd8970db8e1fd8346e0bb2b2b08069e23376/optimiser-controller/src/main/java/eu/nebulouscloud/optimiser/controller/NebulousApp.java#L431

This message `{ state: "FAILED" }` goes out to the channel `"eu.nebulouscloud.optimiser.controller.app_state"`

I assume this is a bug in the UI, since it should show the app in failed state, not deployed.

**Comment by robert-sanfeliu** [comment]
Moved it here: https://openproject.nebulouscloud.eu/projects/nebulous-2nd-release-1/work_packages/create_new?type=1

**Comment by robert-sanfeliu** [comment]
Moved to: https://github.com/eu-nebulous/gui/issues/40
