### ISSUE TITLE
Invalid model sent to solver

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/optimiser-controller#42]
When user defines an APP that with a variable amount of RAM, if the user specifies the initial amount of RAM using Gi Mb, Kb, terminology, optimiser controller will send an invalid model to solver.

For instance, for the following kubevela:

![image](https://github.com/user-attachments/assets/553536a7-169a-45aa-932c-5c826f6482a5)

Optimiser controller will send this message:

```
topic://eu.nebulouscloud.optimiser.controller.model
subject:926f36a5-f1a4-4d97-ae28-94b72a8d8e84
properties:{application=926f36a5-f1a4-4d97-ae28-94b72a8d8e84}
correlationId:null
payload:{"ModelFileName":"926f36a5-f1a4-4d97-ae28-94b72a8d8e84.ampl","ModelFileContent":"# AMPL file for application 'Augmenta-202411041708 Copy' with id 926f36a5-f1a4-4d97-ae28-94b72a8d8e84\n\n# Variables\nvar spec_components_1_properties_memory integer >= 2400.0, <= 12000.0;\nvar spec_components_1_traits_0_properties_replicas integer >= 1.0, <= 5.0 := 1;\nvar spec_components_1_properties_cpu integer >= 8.0, <= 10.0;\n\n# Metrics.  Note that we only emit metrics that are in use.  Values will be provided by the solver.\n## Raw metrics\n## Composite metrics\n\n# Constants\nparam deployed_memory;\n\n# Performance indicators = composite metrics that have at least one variable in their formula\n# Performance indicator formulas\n\n# Cost parameters - for all components, and use of node-candidates tensor\nparam COEFFICIENTS_spec_components_1{1..4};\nvar cost_pi_spec_components_1 = COEFFICIENTS_spec_components_1[1] + COEFFICIENTS_spec_components_1[2] * spec_components_1_properties_cpu + COEFFICIENTS_spec_components_1[3] * spec_components_1_properties_memory + COEFFICIENTS_spec_components_1[4] * spec_components_1_traits_0_properties_replicas;\n\nminimize costfunction:\n    cost_pi_spec_components_1;\n\n# Utility functions\nmaximize utility :\n\t1/exp(0.00000002*(deployed_memory - spec_components_1_properties_memory)^2);\n\n# Default utility function: specified in message to solver\n\n# Constraints. For constraints we don't have name from GUI, must be created\n","DataFileName":"926f36a5-f1a4-4d97-ae28-94b72a8d8e84.dat","DataFileContent":"param:COEFFICIENTS_spec_components_1 := 1 0.1535256463706932 2 0.029447955623598407 3 6.193623848484231E-6 ;","ObjectiveFunction":"utility","Constants":{"deployed_memory":{"Variable":"spec_components_1_properties_memory","Value":"8Gi"}}}
```

Making the solver crash:

```
Received metric subscription request:
{
  "metrics": []
}
AMPL Solver saving the file: /tmp/926f36a5-f1a4-4d97-ae28-94b72a8d8e84.ampl
AMPL Solver saving the file: /tmp/926f36a5-f1a4-4d97-ae28-94b72a8d8e84.dat
terminate called after throwing an instance of 'ampl::AMPLException'
  what():  Error executing "let" command:
        can't convert '8Gi' to a number.
```

Can we modify optimiser controller to support this? Or should we force the user not to use Gi notation?

**Comment by GeirHo** [comment]
Interesting question, Robert!

Thanks for looking into this. The number units can be filtered by the Optimizer Controller, but I thought that they would be unnecessary since there is probably a unit defined in KubeVela for the different option ranges, no? So microcores for CPU and GB for memory. Hence it should not be necessary to give explicit units in the KubeVela file.

On the other hand, if the KubeVela file allows you to write units, we should allow units in the Optimizer Controller since we have the principle that the KubeVela file initially given to the GUI must be deployable, and therefore if there is no issue with 8Gi in KubeVela it should not be a problem for NebulOuS.

All the best,

--- Geir

--

Geir Horn

University of Oslo



Faculty of Mathematics and Natural Sciences

***@***.******@***.***>
Ole-Johan Dahls hus (8464)

+47 93 05 93 35

Postboks 1080 Blindern

Zoom, Viber, Signal, SIP
0316 Oslo

Skype: GeirHorn

Norway

















On Tue, 2024-11-12 at 05:48 -0800, robert-sanfeliu wrote:

When user defines an APP that with a variable amount of RAM, if the user specifies the initial amount of RAM using Gi Mb, Kb, terminology, optimiser controller will send an invalid model to solver.

For instance, for the following kubevela:

image.png (view on web)<https://github.com/user-attachments/assets/553536a7-169a-45aa-932c-5c826f6482a5>

Optimiser controller will send this message:

topic://eu.nebulouscloud.optimiser.controller.model
subject:926f36a5-f1a4-4d97-ae28-94b72a8d8e84
properties:{application=926f36a5-f1a4-4d97-ae28-94b72a8d8e84}
correlationId:null
payload:{"ModelFileName":"926f36a5-f1a4-4d97-ae28-94b72a8d8e84.ampl","ModelFileContent":"# AMPL file for application 'Augmenta-202411041708 Copy' with id 926f36a5-f1a4-4d97-ae28-94b72a8d8e84\n\n# Variables\nvar spec_components_1_properties_memory integer >= 2400.0, <= 12000.0;\nvar spec_components_1_traits_0_properties_replicas integer >= 1.0, <= 5.0 := 1;\nvar spec_components_1_properties_cpu integer >= 8.0, <= 10.0;\n\n# Metrics.  Note that we only emit metrics that are in use.  Values will be provided by the solver.\n## Raw metrics\n## Composite metrics\n\n# Constants\nparam deployed_memory;\n\n# Performance indicators = composite metrics that have at least one variable in their formula\n# Performance indicator formulas\n\n# Cost parameters - for all components, and use of node-candidates tensor\nparam COEFFICIENTS_spec_components_1{1..4};\nvar cost_pi_spec_components_1 = COEFFICIENTS_spec_components_1[1] + COEFFICIENTS_spec_components_1[2] * spec_components_1_properties_cpu + COEFFICIENTS_spec_components_1[3] * spec_components_1_properties_memory + COEFFICIENTS_spec_components_1[4] * spec_components_1_traits_0_properties_replicas;\n\nminimize costfunction:\n    cost_pi_spec_components_1;\n\n# Utility functions\nmaximize utility :\n\t1/exp(0.00000002*(deployed_memory - spec_components_1_properties_memory)^2);\n\n# Default utility function: specified in message to solver\n\n# Constraints. For constraints we don't have name from GUI, must be created\n","DataFileName":"926f36a5-f1a4-4d97-ae28-94b72a8d8e84.dat","DataFileContent":"param:COEFFICIENTS_spec_components_1 := 1 0.1535256463706932 2 0.029447955623598407 3 6.193623848484231E-6 ;","ObjectiveFunction":"utility","Constants":{"deployed_memory":{"Variable":"spec_components_1_properties_memory","Value":"8Gi"}}}


Making the solver crash:

Received metric subscription request:
{
  "metrics": []
}
AMPL Solver saving the file: /tmp/926f36a5-f1a4-4d97-ae28-94b72a8d8e84.ampl
AMPL Solver saving the file: /tmp/926f36a5-f1a4-4d97-ae28-94b72a8d8e84.dat
terminate called after throwing an instance of 'ampl::AMPLException'
  what():  Error executing "let" command:
        can't convert '8Gi' to a number.


Can we modify optimiser controller to support this? Or should we force the user not to use Gi notation?

**Comment by rudi** [comment]
We already try to handle this here: https://github.com/eu-nebulous/optimiser-controller/blob/1de513e781da91f159431437fb901d59c5d6602b/nebulous-requirements-extractor/src/main/java/eu/nebulouscloud/optimiser/kubevela/KubevelaAnalyzer.java#L251

Will investigate.

**Comment by rudi** [comment]
How does the user specify a unit for the memory constraints?  In the above screenshot, the user specifies an initial memory size of 8GB, and a memory constraint range of 2400GB to 12000GB.  I think that's just user error.  Currently the optimiser-controller treats all memory constraints as being in GB.  If we want to have variable units, the UI needs to implement that.

**Comment by rudi** [comment]
We need *some* unit for every number related to memory, since KubeVela makes units mandatory when specifying memory.  Currently I convert everything to GB (and handle MB and GB in KubeVela; should maybe also add TB and KB?), but if the user says "please an initial node with 8GB, and please make sure the solver gives us nodes between 2.4TB and 12TB" that's on them I think!  

... or on us, since the GUI doesn't tell them that that's what they are doing.

Still have to debug why the "8Gi" wasn't converted to a plain "8192" though, so the bug report is in no way invalid.

**Comment by GeirHo** [comment]
I agree, Rudi!

I hope the GUI can generate an error for the user if the initial value for a resource attribute is outside the legal range for that attribute. In this case we should throw an error and not deploy. It is not bad if it is less than the requested amount is below the lower limit, but what if the initial value is above the upper limit?

All the best,

--- Geir

--

Geir Horn

University of Oslo



Faculty of Mathematics and Natural Sciences

***@***.******@***.***>
Ole-Johan Dahls hus (8464)

+47 93 05 93 35

Postboks 1080 Blindern

Zoom, Viber, Signal, SIP
0316 Oslo

Skype: GeirHorn

Norway

















On Wed, 2024-11-13 at 02:51 -0800, Rudolf Schlatte wrote:

We need some unit for every number related to memory, since KubeVela makes units mandatory when specifying memory. Currently I convert everything to GB (and handle MB and GB in KubeVela; should maybe also add TB and KB?), but if the user says "please an initial node with 8GB, and please make sure the solver gives us nodes between 2.4TB and 12TB" that's on them I think!

... or on us, since the GUI doesn't tell them that that's what they are doing.

Still have to debug why the "8Gi" wasn't converted to a plain "8192" though, so the bug report is in no way invalid.

**Comment by robert-sanfeliu** [comment]
@rudi : The docu for Kubevela about units isn't clear: https://kubevela.io/docs/end-user/components/references/#webservice
![image](https://github.com/user-attachments/assets/56aa34e4-f41c-4262-bcdc-1e2fed4db414)


  . Regarding kubernetes, I found: https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#memory-units

@GeirHo: I will add a feature request for the UI. However, this won't be an easy one. 

On a side note, trying to workaround the bug, I tried to input the initial value without units:
![image](https://github.com/user-attachments/assets/4c0d32ef-c769-45d2-8d6b-432a5c626832)

Now I'm getting this error on the solver side:
 
![image](https://github.com/user-attachments/assets/3b7b8734-1c1f-43a8-83a5-b73c39bbdc78)
